In [2]:
from create_species import *
from simulate_interaction import *
from create_community import *
from machine_learning import *
from hyperparameter import *

In [3]:
simulated_data_1 = simulate_interaction(None, main=[],
                                      inter=np.array([["A1", "B1"]]),
                                      weights= {'main': [], 'inter': [1]},
                                      NumberA=50, NumberB=100,
                                      traitsA=[0, 6], traitsB=[0, 6],
                                      abundance=False, specRange=[100, 100])

In [4]:
X = simulated_data_1['A']
Y = simulated_data_1['B']

In [5]:
binary_interactions = minOneInter(simulated_data_1['binar'](3e2))

class_community_C1= createCommunity(X,Y, binary_interactions)
class_community_C1

{'data':         X     Y        A1        A2        A3        A4        A5        A6  \
 0      a1    b1  0.220049  0.392224  0.519877  0.103307  0.020509  0.082303
 1      a1    b2  0.220049  0.392224  0.519877  0.103307  0.020509  0.082303
 2      a1    b3  0.220049  0.392224  0.519877  0.103307  0.020509  0.082303
 3      a1    b4  0.220049  0.392224  0.519877  0.103307  0.020509  0.082303
 4      a1    b5  0.220049  0.392224  0.519877  0.103307  0.020509  0.082303
 ...   ...   ...       ...       ...       ...       ...       ...       ...
 4995  a50   b96  0.744806  0.621427  0.153943  0.252078  0.763151  0.473746
 4996  a50   b97  0.744806  0.621427  0.153943  0.252078  0.763151  0.473746
 4997  a50   b98  0.744806  0.621427  0.153943  0.252078  0.763151  0.473746
 4998  a50   b99  0.744806  0.621427  0.153943  0.252078  0.763151  0.473746
 4999  a50  b100  0.744806  0.621427  0.153943  0.252078  0.763151  0.473746

             B1        B2        B3        B4        B5        B6    target
 0     0.554262  0.201497  0.598168  0.321227  0.937218  0.351307  negative
 1     0.240440  0.052236  0.679376  0.712086  0.511005  0.345725  positive
 2     0.053010  0.927847  0.002979  0.031931  0.824025  0.312266  positive
 3     0.856577  0.078558  0.463723  0.773029  0.167946  0.815044  positive
 4     0.415313  0.309463  0.924364  0.793046  0.128646  0.450695  negative
 ...        ...       ...       ...       ...       ...       ...       ...
 4995  0.459322  0.521029  0.904058  0.972598  0.651525  0.174716  positive
 4996  0.759874  0.746792  0.284996  0.020193  0.779698  0.995294  negative
 4997  0.863722  0.834731  0.153054  0.374362  0.112776  0.157571  negative
 4998  0.013790  0.186785  0.841001  0.203053  0.718653  0.231585  positive
 4999  0.438386  0.595809  0.646948  0.979375  0.477054  0.413430  positive

 [5000 rows x 15 columns],
 'target': 0       negative
 1       positive
 2       positive
 3       positive
 4       negative
           ...
 4995    positive
 4996    negative
 4997    negative
 4998    positive
 4999    positive
 Name: target, Length: 5000, dtype: object,
 'type': 'Classification',
 'class': ['Community', 'Classification']}

In [6]:
class_community_C1['data']['target'].value_counts()/class_community_C1['data']['target'].value_counts().sum()

target
negative    0.5602
positive    0.4398
Name: count, dtype: float64

In [7]:
poisson_interactions = minOneInter(simulated_data_1['poisson'](3e2))

class_community_R1= createCommunity(X,Y, poisson_interactions, log= False)
class_community_R1

{'data':         X     Y        A1        A2        A3        A4        A5        A6  \
 0      a1    b1  0.220049  0.392224  0.519877  0.103307  0.020509  0.082303
 1      a1    b2  0.220049  0.392224  0.519877  0.103307  0.020509  0.082303
 2      a1    b3  0.220049  0.392224  0.519877  0.103307  0.020509  0.082303
 3      a1    b4  0.220049  0.392224  0.519877  0.103307  0.020509  0.082303
 4      a1    b5  0.220049  0.392224  0.519877  0.103307  0.020509  0.082303
 ...   ...   ...       ...       ...       ...       ...       ...       ...
 4995  a50   b96  0.744806  0.621427  0.153943  0.252078  0.763151  0.473746
 4996  a50   b97  0.744806  0.621427  0.153943  0.252078  0.763151  0.473746
 4997  a50   b98  0.744806  0.621427  0.153943  0.252078  0.763151  0.473746
 4998  a50   b99  0.744806  0.621427  0.153943  0.252078  0.763151  0.473746
 4999  a50  b100  0.744806  0.621427  0.153943  0.252078  0.763151  0.473746

             B1        B2        B3        B4        B5        B6  target
 0     0.554262  0.201497  0.598168  0.321227  0.937218  0.351307     0.0
 1     0.240440  0.052236  0.679376  0.712086  0.511005  0.345725     1.0
 2     0.053010  0.927847  0.002979  0.031931  0.824025  0.312266     2.0
 3     0.856577  0.078558  0.463723  0.773029  0.167946  0.815044     1.0
 4     0.415313  0.309463  0.924364  0.793046  0.128646  0.450695     0.0
 ...        ...       ...       ...       ...       ...       ...     ...
 4995  0.459322  0.521029  0.904058  0.972598  0.651525  0.174716     1.0
 4996  0.759874  0.746792  0.284996  0.020193  0.779698  0.995294     0.0
 4997  0.863722  0.834731  0.153054  0.374362  0.112776  0.157571     0.0
 4998  0.013790  0.186785  0.841001  0.203053  0.718653  0.231585     1.0
 4999  0.438386  0.595809  0.646948  0.979375  0.477054  0.413430     3.0

 [5000 rows x 15 columns],
 'target': 0       0.0
 1       1.0
 2       2.0
 3       1.0
 4       0.0
        ...
 4995    1.0
 4996    0.0
 4997    0.0
 4998    1.0
 4999    3.0
 Name: target, Length: 5000, dtype: float64,
 'type': 'Regression',
 'class': ['Community', 'Regression']}

In [8]:
class_community_R1['data']['target'].value_counts()/class_community_R1['data']['target'].value_counts().sum()

target
0.0    0.5602
1.0    0.3212
2.0    0.0958
3.0    0.0180
4.0    0.0048
Name: count, dtype: float64

### #2 Without effects but with abundances - baseline with abundances
- wide and weak effects (gaussian with sd = 100)
- species abundances
- 50*100 base network size

In [9]:
simulated_data_2 = simulate_interaction(None, main=[],
                                      inter=np.array([["A1", "B1"]]),
                                      weights= {'main': [], 'inter': [1]},
                                      NumberA=50, NumberB=100,
                                      traitsA=[0, 5], traitsB=[0, 5],
                                      abundance=lambda a, b, rng: np.random.exponential(2, size=a),
                                      specRange=[100, 100])

In [10]:
X = simulated_data_2['A']
Y = simulated_data_2['B']

In [11]:
binary_interactions_2 = minOneInter(simulated_data_2['binar'](4e3))

class_community_C2= createCommunity(X,Y, binary_interactions_2)
class_community_C2

{'data':         X     Y        A1        A2        A3        A4        A5        B1  \
 0      a1    b1  0.079852  0.578201  0.660256  0.655486  0.070026  0.522818
 1      a1    b2  0.079852  0.578201  0.660256  0.655486  0.070026  0.437543
 2      a1    b3  0.079852  0.578201  0.660256  0.655486  0.070026  0.541638
 3      a1    b4  0.079852  0.578201  0.660256  0.655486  0.070026  0.395808
 4      a1    b5  0.079852  0.578201  0.660256  0.655486  0.070026  0.324174
 ...   ...   ...       ...       ...       ...       ...       ...       ...
 4995  a50   b96  0.950202  0.841200  0.825985  0.793957  0.089526  0.007178
 4996  a50   b97  0.950202  0.841200  0.825985  0.793957  0.089526  0.198117
 4997  a50   b98  0.950202  0.841200  0.825985  0.793957  0.089526  0.462598
 4998  a50   b99  0.950202  0.841200  0.825985  0.793957  0.089526  0.706878
 4999  a50  b100  0.950202  0.841200  0.825985  0.793957  0.089526  0.225249

             B2        B3        B4        B5    target
 0     0.982372  0.259852  0.781599  0.356796  positive
 1     0.506847  0.673902  0.035201  0.355766  positive
 2     0.895385  0.504501  0.989449  0.608278  positive
 3     0.334298  0.832308  0.994252  0.532171  positive
 4     0.989838  0.837020  0.612241  0.309439  positive
 ...        ...       ...       ...       ...       ...
 4995  0.764120  0.840270  0.328143  0.407591  positive
 4996  0.906861  0.862274  0.467833  0.068166  positive
 4997  0.239706  0.246344  0.021074  0.165421  positive
 4998  0.155387  0.550871  0.819165  0.015108  positive
 4999  0.315080  0.821098  0.729278  0.051310  positive

 [5000 rows x 13 columns],
 'target': 0       positive
 1       positive
 2       positive
 3       positive
 4       positive
           ...
 4995    positive
 4996    positive
 4997    positive
 4998    positive
 4999    positive
 Name: target, Length: 5000, dtype: object,
 'type': 'Classification',
 'class': ['Community', 'Classification']}

In [12]:
class_community_C2['data']['target'].value_counts()/class_community_C2['data']['target'].value_counts().sum()

target
positive    0.9138
negative    0.0862
Name: count, dtype: float64

In [13]:
poisson_interactions_2 = simulated_data_2['poisson'](4e3)

class_community_R2= createCommunity(X,Y, poisson_interactions_2, log= False)
class_community_R2

{'data':         X     Y        A1        A2        A3        A4        A5        B1  \
 0      a1    b1  0.079852  0.578201  0.660256  0.655486  0.070026  0.522818
 1      a1    b2  0.079852  0.578201  0.660256  0.655486  0.070026  0.437543
 2      a1    b3  0.079852  0.578201  0.660256  0.655486  0.070026  0.541638
 3      a1    b4  0.079852  0.578201  0.660256  0.655486  0.070026  0.395808
 4      a1    b5  0.079852  0.578201  0.660256  0.655486  0.070026  0.324174
 ...   ...   ...       ...       ...       ...       ...       ...       ...
 4995  a50   b96  0.950202  0.841200  0.825985  0.793957  0.089526  0.007178
 4996  a50   b97  0.950202  0.841200  0.825985  0.793957  0.089526  0.198117
 4997  a50   b98  0.950202  0.841200  0.825985  0.793957  0.089526  0.462598
 4998  a50   b99  0.950202  0.841200  0.825985  0.793957  0.089526  0.706878
 4999  a50  b100  0.950202  0.841200  0.825985  0.793957  0.089526  0.225249

             B2        B3        B4        B5  target
 0     0.982372  0.259852  0.781599  0.356796    15.0
 1     0.506847  0.673902  0.035201  0.355766     7.0
 2     0.895385  0.504501  0.989449  0.608278     8.0
 3     0.334298  0.832308  0.994252  0.532171     6.0
 4     0.989838  0.837020  0.612241  0.309439     2.0
 ...        ...       ...       ...       ...     ...
 4995  0.764120  0.840270  0.328143  0.407591     2.0
 4996  0.906861  0.862274  0.467833  0.068166    80.0
 4997  0.239706  0.246344  0.021074  0.165421    33.0
 4998  0.155387  0.550871  0.819165  0.015108    24.0
 4999  0.315080  0.821098  0.729278  0.051310    19.0

 [5000 rows x 13 columns],
 'target': 0       15.0
 1        7.0
 2        8.0
 3        6.0
 4        2.0
         ...
 4995     2.0
 4996    80.0
 4997    33.0
 4998    24.0
 4999    19.0
 Name: target, Length: 5000, dtype: float64,
 'type': 'Regression',
 'class': ['Community', 'Regression']}

In [14]:
class_community_R2['data']['target'].value_counts()/class_community_R2['data']['target'].value_counts().sum()

target
0.0      0.0862
1.0      0.0684
2.0      0.0526
3.0      0.0484
6.0      0.0380
          ...
123.0    0.0002
169.0    0.0002
142.0    0.0002
165.0    0.0002
230.0    0.0002
Name: count, Length: 239, dtype: float64

### #3 With effects and w/o abundances - Network Sizes
- with strong effects (gaussian with small sd and high interaction weight)
- without species abundances

In [15]:
simulated_data_3 = simulate_interaction(None, main=[],
                                      inter=np.array([["A1", "B1"], ["A2", "B2"], ["A3", "B3"] ]),
                                      weights= {'main': [], 'inter': [10, 10, 10]},
                                      NumberA=100, NumberB=200,
                                      traitsA=[0, 6], traitsB=[0, 6],
                                      abundance= False,
                                      specRange=[0.5, 1.2])

In [16]:
X = simulated_data_3['A']
Y = simulated_data_3['B']

In [17]:
binary_interactions_3 = simulated_data_3['binar'](1.2e-1)

class_community_C3= createCommunity(X,Y, binary_interactions_3 )
class_community_C3

{'data':           X     Y        A1        A2        A3        A4        A5        A6  \
 0        a1    b1  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 1        a1    b2  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 2        a1    b3  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 3        a1    b4  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 4        a1    b5  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 ...     ...   ...       ...       ...       ...       ...       ...       ...
 19995  a100  b196  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19996  a100  b197  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19997  a100  b198  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19998  a100  b199  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19999  a100  b200  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149

              B1        B2        B3        B4        B5        B6    target
 0      0.905394  0.627141  0.004124  0.495460  0.677577  0.208311  negative
 1      0.224414  0.228480  0.016449  0.815453  0.078746  0.322951  negative
 2      0.973814  0.019673  0.702359  0.935972  0.218404  0.329397  negative
 3      0.201055  0.989632  0.955579  0.835887  0.658748  0.769800  negative
 4      0.226728  0.434467  0.392817  0.756376  0.728210  0.284380  negative
 ...         ...       ...       ...       ...       ...       ...       ...
 19995  0.101379  0.985636  0.209741  0.109177  0.153338  0.845952  negative
 19996  0.749521  0.252868  0.423237  0.166023  0.371363  0.610882  negative
 19997  0.014416  0.248335  0.593786  0.911374  0.425073  0.918091  negative
 19998  0.228933  0.846219  0.739485  0.118318  0.019194  0.367549  negative
 19999  0.083377  0.793793  0.002202  0.738356  0.321049  0.847341  negative

 [20000 rows x 15 columns],
 'target': 0        negative
 1        negative
 2        negative
 3        negative
 4        negative
            ...
 19995    negative
 19996    negative
 19997    negative
 19998    negative
 19999    negative
 Name: target, Length: 20000, dtype: object,
 'type': 'Classification',
 'class': ['Community', 'Classification']}

In [18]:
class_community_C3['target'].value_counts()/class_community_C3['target'].value_counts().sum()

target
negative    0.5663
positive    0.4337
Name: count, dtype: float64

In [19]:
poisson_interactions_3 = simulated_data_3['poisson'](1.2e-1)

class_community_R3= createCommunity(X,Y, poisson_interactions_3, log= False)
class_community_R3

{'data':           X     Y        A1        A2        A3        A4        A5        A6  \
 0        a1    b1  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 1        a1    b2  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 2        a1    b3  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 3        a1    b4  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 4        a1    b5  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 ...     ...   ...       ...       ...       ...       ...       ...       ...
 19995  a100  b196  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19996  a100  b197  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19997  a100  b198  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19998  a100  b199  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19999  a100  b200  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149

              B1        B2        B3        B4        B5        B6  target
 0      0.905394  0.627141  0.004124  0.495460  0.677577  0.208311     0.0
 1      0.224414  0.228480  0.016449  0.815453  0.078746  0.322951     0.0
 2      0.973814  0.019673  0.702359  0.935972  0.218404  0.329397     0.0
 3      0.201055  0.989632  0.955579  0.835887  0.658748  0.769800     0.0
 4      0.226728  0.434467  0.392817  0.756376  0.728210  0.284380     0.0
 ...         ...       ...       ...       ...       ...       ...     ...
 19995  0.101379  0.985636  0.209741  0.109177  0.153338  0.845952     0.0
 19996  0.749521  0.252868  0.423237  0.166023  0.371363  0.610882     0.0
 19997  0.014416  0.248335  0.593786  0.911374  0.425073  0.918091     0.0
 19998  0.228933  0.846219  0.739485  0.118318  0.019194  0.367549     0.0
 19999  0.083377  0.793793  0.002202  0.738356  0.321049  0.847341     0.0

 [20000 rows x 15 columns],
 'target': 0        0.0
 1        0.0
 2        0.0
 3        0.0
 4        0.0
         ...
 19995    0.0
 19996    0.0
 19997    0.0
 19998    0.0
 19999    0.0
 Name: target, Length: 20000, dtype: float64,
 'type': 'Regression',
 'class': ['Community', 'Regression']}

In [20]:
class_community_R3['target'].value_counts()/class_community_R3['target'].value_counts().sum()

target
0.0     0.56630
1.0     0.15160
2.0     0.08700
3.0     0.05785
4.0     0.03645
5.0     0.02605
6.0     0.01765
7.0     0.01380
8.0     0.00890
9.0     0.00685
10.0    0.00535
11.0    0.00410
12.0    0.00310
13.0    0.00235
14.0    0.00230
15.0    0.00205
20.0    0.00145
17.0    0.00135
18.0    0.00130
19.0    0.00095
16.0    0.00090
23.0    0.00050
22.0    0.00045
25.0    0.00030
24.0    0.00015
27.0    0.00015
21.0    0.00015
26.0    0.00010
32.0    0.00010
28.0    0.00005
33.0    0.00005
37.0    0.00005
29.0    0.00005
31.0    0.00005
30.0    0.00005
35.0    0.00005
34.0    0.00005
36.0    0.00005
Name: count, dtype: float64

### #4 With effects and w/o abundances - Observation time
Varying observation times results in diffrent class distributions (classification). We choose times so, that the positive interaction had class proportions of 10 \%, 25 \% and 50 \%:

In [21]:
simulated_data_4 = simulate_interaction(None, main=[],
                                      inter=np.array([["A1", "B1"], ["A2", "B2"], ["A3", "B3"] ]),
                                      weights= {'main': [], 'inter': [10, 10, 10]},
                                      NumberA=100, NumberB=200,
                                      traitsA=[0, 6], traitsB=[0, 6],
                                      abundance= False,
                                      specRange=[0.5, 1.2])

In [22]:
# Gerando os valores
obsC = {
    'low': simulated_data_4['binar'](0.7e-2),
    'mid': simulated_data_4['binar'](3.2e-2),
    'high': simulated_data_4['binar'](1.2e-1)
}

obsR = {
    'low': simulated_data_4['poisson'](0.7e-2),
    'mid': simulated_data_4['poisson'](3.2e-2),
    'high': simulated_data_4['poisson'](1.2e-1)
}

In [23]:
class_community_C4_low = createCommunity(X, Y, obsC['low'])
class_community_C4_low

{'data':           X     Y        A1        A2        A3        A4        A5        A6  \
 0        a1    b1  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 1        a1    b2  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 2        a1    b3  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 3        a1    b4  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 4        a1    b5  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 ...     ...   ...       ...       ...       ...       ...       ...       ...
 19995  a100  b196  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19996  a100  b197  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19997  a100  b198  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19998  a100  b199  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19999  a100  b200  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149

              B1        B2        B3        B4        B5        B6    target
 0      0.905394  0.627141  0.004124  0.495460  0.677577  0.208311  negative
 1      0.224414  0.228480  0.016449  0.815453  0.078746  0.322951  negative
 2      0.973814  0.019673  0.702359  0.935972  0.218404  0.329397  negative
 3      0.201055  0.989632  0.955579  0.835887  0.658748  0.769800  negative
 4      0.226728  0.434467  0.392817  0.756376  0.728210  0.284380  negative
 ...         ...       ...       ...       ...       ...       ...       ...
 19995  0.101379  0.985636  0.209741  0.109177  0.153338  0.845952  negative
 19996  0.749521  0.252868  0.423237  0.166023  0.371363  0.610882  negative
 19997  0.014416  0.248335  0.593786  0.911374  0.425073  0.918091  negative
 19998  0.228933  0.846219  0.739485  0.118318  0.019194  0.367549  negative
 19999  0.083377  0.793793  0.002202  0.738356  0.321049  0.847341  negative

 [20000 rows x 15 columns],
 'target': 0        negative
 1        negative
 2        negative
 3        negative
 4        negative
            ...
 19995    negative
 19996    negative
 19997    negative
 19998    negative
 19999    negative
 Name: target, Length: 20000, dtype: object,
 'type': 'Classification',
 'class': ['Community', 'Classification']}

In [24]:
class_community_C4_low['data']['target'].value_counts()/class_community_C4_low['data']['target'].value_counts().sum()

target
negative    0.9265
positive    0.0735
Name: count, dtype: float64

In [25]:
class_community_C4_mid = createCommunity(X, Y, obsC['mid'])
class_community_C4_mid

{'data':           X     Y        A1        A2        A3        A4        A5        A6  \
 0        a1    b1  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 1        a1    b2  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 2        a1    b3  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 3        a1    b4  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 4        a1    b5  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 ...     ...   ...       ...       ...       ...       ...       ...       ...
 19995  a100  b196  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19996  a100  b197  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19997  a100  b198  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19998  a100  b199  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19999  a100  b200  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149

              B1        B2        B3        B4        B5        B6    target
 0      0.905394  0.627141  0.004124  0.495460  0.677577  0.208311  negative
 1      0.224414  0.228480  0.016449  0.815453  0.078746  0.322951  negative
 2      0.973814  0.019673  0.702359  0.935972  0.218404  0.329397  negative
 3      0.201055  0.989632  0.955579  0.835887  0.658748  0.769800  negative
 4      0.226728  0.434467  0.392817  0.756376  0.728210  0.284380  negative
 ...         ...       ...       ...       ...       ...       ...       ...
 19995  0.101379  0.985636  0.209741  0.109177  0.153338  0.845952  negative
 19996  0.749521  0.252868  0.423237  0.166023  0.371363  0.610882  negative
 19997  0.014416  0.248335  0.593786  0.911374  0.425073  0.918091  negative
 19998  0.228933  0.846219  0.739485  0.118318  0.019194  0.367549  negative
 19999  0.083377  0.793793  0.002202  0.738356  0.321049  0.847341  negative

 [20000 rows x 15 columns],
 'target': 0        negative
 1        negative
 2        negative
 3        negative
 4        negative
            ...
 19995    negative
 19996    negative
 19997    negative
 19998    negative
 19999    negative
 Name: target, Length: 20000, dtype: object,
 'type': 'Classification',
 'class': ['Community', 'Classification']}

In [26]:
class_community_C4_mid['data']['target'].value_counts()/class_community_C4_mid['data']['target'].value_counts().sum()

target
negative    0.7686
positive    0.2314
Name: count, dtype: float64

In [27]:
class_community_C4_high = createCommunity(X, Y, obsC['high'])
class_community_C4_high

{'data':           X     Y        A1        A2        A3        A4        A5        A6  \
 0        a1    b1  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 1        a1    b2  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 2        a1    b3  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 3        a1    b4  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 4        a1    b5  0.798305  0.867304  0.389030  0.377349  0.724504  0.298213
 ...     ...   ...       ...       ...       ...       ...       ...       ...
 19995  a100  b196  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19996  a100  b197  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19997  a100  b198  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19998  a100  b199  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149
 19999  a100  b200  0.621842  0.691329  0.109172  0.332094  0.391581  0.883149

              B1        B2        B3        B4        B5        B6    target
 0      0.905394  0.627141  0.004124  0.495460  0.677577  0.208311  negative
 1      0.224414  0.228480  0.016449  0.815453  0.078746  0.322951  negative
 2      0.973814  0.019673  0.702359  0.935972  0.218404  0.329397  negative
 3      0.201055  0.989632  0.955579  0.835887  0.658748  0.769800  negative
 4      0.226728  0.434467  0.392817  0.756376  0.728210  0.284380  negative
 ...         ...       ...       ...       ...       ...       ...       ...
 19995  0.101379  0.985636  0.209741  0.109177  0.153338  0.845952  negative
 19996  0.749521  0.252868  0.423237  0.166023  0.371363  0.610882  negative
 19997  0.014416  0.248335  0.593786  0.911374  0.425073  0.918091  negative
 19998  0.228933  0.846219  0.739485  0.118318  0.019194  0.367549  negative
 19999  0.083377  0.793793  0.002202  0.738356  0.321049  0.847341  negative

 [20000 rows x 15 columns],
 'target': 0        negative
 1        negative
 2        negative
 3        negative
 4        negative
            ...
 19995    negative
 19996    negative
 19997    negative
 19998    negative
 19999    negative
 Name: target, Length: 20000, dtype: object,
 'type': 'Classification',
 'class': ['Community', 'Classification']}

In [28]:
class_community_C4_high['data']['target'].value_counts()/class_community_C4_high['data']['target'].value_counts().sum()

target
negative    0.56745
positive    0.43255
Name: count, dtype: float64

In [29]:
class_community_R4_low = createCommunity(X, Y, obsR['low'])
class_community_R4_low

{'data':           X     Y        A1        A2        A3        A4        A5        A6  \
 0        a1    b1  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 1        a1    b2  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 2        a1    b3  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 3        a1    b4  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 4        a1    b5  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 ...     ...   ...       ...       ...       ...       ...       ...       ...
 19995  a100  b196  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945
 19996  a100  b197  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945
 19997  a100  b198  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945
 19998  a100  b199  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945
 19999  a100  b200  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945

              B1        B2        B3        B4        B5        B6  target
 0      0.644689  0.486824  0.004116  0.402434  0.517351  0.189223     0.0
 1      0.202462  0.205778  0.016315  0.596335  0.075800  0.279865     0.0
 2      0.679968  0.019482  0.532015  0.660610  0.197542  0.284726     0.0
 3      0.183201  0.687950  0.670686  0.607528  0.506063  0.570866     0.0
 4      0.204351  0.360793  0.331328  0.563253  0.547086  0.250276     0.0
 ...         ...       ...       ...       ...       ...       ...     ...
 19995  0.096563  0.685939  0.190406  0.103619  0.142660  0.612995     0.0
 19996  0.559342  0.225435  0.352934  0.153599  0.315805  0.476782     0.0
 19997  0.014313  0.221811  0.466112  0.647822  0.354223  0.651331     0.0
 19998  0.206147  0.613140  0.553589  0.111825  0.019012  0.313020     0.0
 19999  0.080083  0.584332  0.002199  0.552940  0.278426  0.613748     0.0

 [20000 rows x 15 columns],
 'target': 0        0.0
 1        0.0
 2        0.0
 3        0.0
 4        0.0
         ...
 19995    0.0
 19996    0.0
 19997    0.0
 19998    0.0
 19999    0.0
 Name: target, Length: 20000, dtype: float64,
 'type': 'Regression',
 'class': ['Community', 'Regression']}

In [30]:
class_community_R4_low['data']['target'].value_counts()/class_community_R4_low['data']['target'].value_counts().sum()

target
0.000000    0.92650
0.693147    0.06345
1.098612    0.00810
1.386294    0.00155
1.609438    0.00040
Name: count, dtype: float64

In [31]:
class_community_R4_mid = createCommunity(X, Y, obsR['mid'])
class_community_R4_mid

{'data':           X     Y        A1        A2        A3        A4        A5        A6  \
 0        a1    b1  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 1        a1    b2  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 2        a1    b3  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 3        a1    b4  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 4        a1    b5  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 ...     ...   ...       ...       ...       ...       ...       ...       ...
 19995  a100  b196  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945
 19996  a100  b197  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945
 19997  a100  b198  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945
 19998  a100  b199  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945
 19999  a100  b200  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945

              B1        B2        B3        B4        B5        B6  target
 0      0.644689  0.486824  0.004116  0.402434  0.517351  0.189223     0.0
 1      0.202462  0.205778  0.016315  0.596335  0.075800  0.279865     0.0
 2      0.679968  0.019482  0.532015  0.660610  0.197542  0.284726     0.0
 3      0.183201  0.687950  0.670686  0.607528  0.506063  0.570866     0.0
 4      0.204351  0.360793  0.331328  0.563253  0.547086  0.250276     0.0
 ...         ...       ...       ...       ...       ...       ...     ...
 19995  0.096563  0.685939  0.190406  0.103619  0.142660  0.612995     0.0
 19996  0.559342  0.225435  0.352934  0.153599  0.315805  0.476782     0.0
 19997  0.014313  0.221811  0.466112  0.647822  0.354223  0.651331     0.0
 19998  0.206147  0.613140  0.553589  0.111825  0.019012  0.313020     0.0
 19999  0.080083  0.584332  0.002199  0.552940  0.278426  0.613748     0.0

 [20000 rows x 15 columns],
 'target': 0        0.0
 1        0.0
 2        0.0
 3        0.0
 4        0.0
         ...
 19995    0.0
 19996    0.0
 19997    0.0
 19998    0.0
 19999    0.0
 Name: target, Length: 20000, dtype: float64,
 'type': 'Regression',
 'class': ['Community', 'Regression']}

In [32]:
class_community_R4_mid['data']['target'].value_counts()/class_community_R4_mid['data']['target'].value_counts().sum()

target
0.000000    0.76860
0.693147    0.14415
1.098612    0.04705
1.386294    0.02095
1.609438    0.00900
1.791759    0.00390
1.945910    0.00325
2.079442    0.00125
2.197225    0.00105
2.397895    0.00025
2.302585    0.00025
2.484907    0.00015
2.639057    0.00010
2.564949    0.00005
Name: count, dtype: float64

In [33]:
class_community_R4_high = createCommunity(X, Y, obsR['high'])
class_community_R4_high

{'data':           X     Y        A1        A2        A3        A4        A5        A6  \
 0        a1    b1  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 1        a1    b2  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 2        a1    b3  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 3        a1    b4  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 4        a1    b5  0.586845  0.624496  0.328606  0.320160  0.544939  0.260989
 ...     ...   ...       ...       ...       ...       ...       ...       ...
 19995  a100  b196  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945
 19996  a100  b197  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945
 19997  a100  b198  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945
 19998  a100  b199  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945
 19999  a100  b200  0.483562  0.525515  0.103613  0.286752  0.330441  0.632945

              B1        B2        B3        B4        B5        B6  target
 0      0.644689  0.486824  0.004116  0.402434  0.517351  0.189223     0.0
 1      0.202462  0.205778  0.016315  0.596335  0.075800  0.279865     0.0
 2      0.679968  0.019482  0.532015  0.660610  0.197542  0.284726     0.0
 3      0.183201  0.687950  0.670686  0.607528  0.506063  0.570866     0.0
 4      0.204351  0.360793  0.331328  0.563253  0.547086  0.250276     0.0
 ...         ...       ...       ...       ...       ...       ...     ...
 19995  0.096563  0.685939  0.190406  0.103619  0.142660  0.612995     0.0
 19996  0.559342  0.225435  0.352934  0.153599  0.315805  0.476782     0.0
 19997  0.014313  0.221811  0.466112  0.647822  0.354223  0.651331     0.0
 19998  0.206147  0.613140  0.553589  0.111825  0.019012  0.313020     0.0
 19999  0.080083  0.584332  0.002199  0.552940  0.278426  0.613748     0.0

 [20000 rows x 15 columns],
 'target': 0        0.0
 1        0.0
 2        0.0
 3        0.0
 4        0.0
         ...
 19995    0.0
 19996    0.0
 19997    0.0
 19998    0.0
 19999    0.0
 Name: target, Length: 20000, dtype: float64,
 'type': 'Regression',
 'class': ['Community', 'Regression']}

In [34]:
class_community_R4_high['data']['target'].value_counts()/class_community_R4_high['data']['target'].value_counts().sum()

target
0.000000    0.56745
0.693147    0.14830
1.098612    0.08870
1.386294    0.05860
1.609438    0.03595
1.791759    0.02575
1.945910    0.01860
2.079442    0.01200
2.197225    0.00920
2.302585    0.00685
2.397895    0.00570
2.484907    0.00455
2.564949    0.00365
2.639057    0.00285
2.833213    0.00180
2.708050    0.00165
2.772589    0.00160
2.890372    0.00120
2.944439    0.00090
2.995732    0.00075
3.044522    0.00065
3.091042    0.00065
3.135494    0.00040
3.258097    0.00040
3.178054    0.00035
3.218876    0.00030
3.332205    0.00025
3.367296    0.00020
3.295837    0.00020
3.465736    0.00015
3.583519    0.00010
3.526361    0.00010
3.433987    0.00005
3.401197    0.00005
3.610918    0.00005
3.555348    0.00005
Name: count, dtype: float64

### Conjunto de dados do Dado Real

In [35]:
planta_polinizador_bruto = pd.read_csv("plant_pollinator_database.csv").iloc[:, 1:]
planta_polinizador_bruto

,crop,type,season,diameter,corolla,colour,nectar,b.system,s.pollination,inflorescence,composite,visitor,guild,tongue,body,sociality,feeding
0,Vaccinium_corymbosum,arboreous,sprisum,NaN,CAMPANULATE,white,yes,insects,no,yes,no,Andrena_wilkella,ANDRENIDAE,NaN,10.5,no,oligolectic
1,Vaccinium_corymbosum,arboreous,sprisum,NaN,CAMPANULATE,white,yes,insects,no,yes,no,Andrena_barbilabris,ANDRENIDAE,NaN,10.5,no,polylectic
2,Brassica_napus,herbaceous,summer,12.5,OPEN,yellow,yes,wind/insects,no,yes,no,Andrena_cineraria,ANDRENIDAE,NaN,12.0,no,polylectic
3,Brassica_napus,herbaceous,summer,12.5,OPEN,yellow,yes,wind/insects,no,yes,no,Andrena_flavipes,ANDRENIDAE,NaN,11.0,no,polylectic
4,Brassica_napus,herbaceous,summer,12.5,OPEN,yellow,yes,wind/insects,no,yes,no,Andrena_gravida,ANDRENIDAE,NaN,13.0,no,polylectic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791,Allium_oleraceum,herbaceous,summer,NaN,CAMPANULATE,purple,yes,insects,no,yes,no,Dolichovespula_saxonica,WASPS,NaN,13.0,yes,polylectic
792,Jatropha_curcas,arboreous,spriaut,2.0,OPEN,green,yes,insects,no,yes,no,Bembecinus_tridens,WASPS,NaN,9.0,no,NaN
793,Malus_domestica,arboreous,spring,35.0,OPEN,white,yes,insects,no,yes,no,Vespula_vulgaris,WASPS,NaN,12.5,yes,polylectic
794,Phaseolus_coccineus,herbaceous,summer,NaN,OPEN,white,yes,insects,no,yes,no,Philanthus_triangulum,WASPS,NaN,15.0,no,polylectic
795,Capparis_spinosa,arboreous,summer,50.0,OPEN,white,yes,insects,no,solitary,no,Bembecinus_tridens,WASPS,NaN,9.0,no,NaN

In [36]:
planta_polinizador_bruto = pd.read_csv("plant_pollinator_database.csv").iloc[:, 1:]

planta_polinizador_bruto['season'] = planta_polinizador_bruto['season'].fillna('')
planta_polinizador_bruto['sociality'] = planta_polinizador_bruto['sociality'].replace({'no': 0, 'yes': 1})
planta_polinizador_bruto['nectar'] = planta_polinizador_bruto['nectar'].replace({'no': 0, 'yes': 1})

color_mapping = {'red': 0, 'yellow': 1, 'blue': 2, 'green': 3, 'white': 4}
planta_polinizador_bruto['colour'] = planta_polinizador_bruto['colour'].map(color_mapping)

corolla_mapping = {'CAMPANULATE': 0, 'OPEN': 1, 'TUBULAR': 2}
feeding_mapping = {'polylectic': 0, 'parasitic': 1, 'oligolectic': 2}

planta_polinizador_bruto['corolla'] = planta_polinizador_bruto['corolla'].map(corolla_mapping)
planta_polinizador_bruto['feeding'] = planta_polinizador_bruto['feeding'].map(feeding_mapping)

colunas_para_imputar = ['diameter', 'corolla', 'colour', 'nectar', 'tongue', 'body', 'sociality', 'feeding']
dados_para_imputar = planta_polinizador_bruto[colunas_para_imputar]

imputador = IterativeImputer(random_state=42)
dados_imputados = imputador.fit_transform(dados_para_imputar)

planta_polinizador_bruto[colunas_para_imputar] = dados_imputados

planta_polinizador_bruto

C:\Users\maria\AppData\Local\Temp\ipykernel_10536\4010488003.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  planta_polinizador_bruto['sociality'] = planta_polinizador_bruto['sociality'].replace({'no': 0, 'yes': 1})
C:\Users\maria\AppData\Local\Temp\ipykernel_10536\4010488003.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  planta_polinizador_bruto['nectar'] = planta_polinizador_bruto['nectar'].replace({'no': 0, 'yes': 1})
c:\Users\maria\Desktop\PythonTraitMatching-Prediction\venv\Lib\site-packages\sklearn\impute\_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

,crop,type,season,diameter,corolla,colour,nectar,b.system,s.pollination,inflorescence,composite,visitor,guild,tongue,body,sociality,feeding
0,Vaccinium_corymbosum,arboreous,sprisum,72.784872,0.0,4.000000,1.0,insects,no,yes,no,Andrena_wilkella,ANDRENIDAE,1.872272,10.5,0.0,2.000000
1,Vaccinium_corymbosum,arboreous,sprisum,55.424141,0.0,4.000000,1.0,insects,no,yes,no,Andrena_barbilabris,ANDRENIDAE,3.465985,10.5,0.0,0.000000
2,Brassica_napus,herbaceous,summer,12.500000,1.0,1.000000,1.0,wind/insects,no,yes,no,Andrena_cineraria,ANDRENIDAE,7.436739,12.0,0.0,0.000000
3,Brassica_napus,herbaceous,summer,12.500000,1.0,1.000000,1.0,wind/insects,no,yes,no,Andrena_flavipes,ANDRENIDAE,6.738133,11.0,0.0,0.000000
4,Brassica_napus,herbaceous,summer,12.500000,1.0,1.000000,1.0,wind/insects,no,yes,no,Andrena_gravida,ANDRENIDAE,8.135346,13.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791,Allium_oleraceum,herbaceous,summer,60.001037,0.0,2.746336,1.0,insects,no,yes,no,Dolichovespula_saxonica,WASPS,5.777719,13.0,1.0,0.000000
792,Jatropha_curcas,arboreous,spriaut,2.000000,1.0,3.000000,1.0,insects,no,yes,no,Bembecinus_tridens,WASPS,5.232198,9.0,0.0,0.080110
793,Malus_domestica,arboreous,spring,35.000000,1.0,4.000000,1.0,insects,no,yes,no,Vespula_vulgaris,WASPS,5.381072,12.5,1.0,0.000000
794,Phaseolus_coccineus,herbaceous,summer,16.993078,1.0,4.000000,1.0,insects,no,yes,no,Philanthus_triangulum,WASPS,7.998989,15.0,0.0,0.000000
795,Capparis_spinosa,arboreous,summer,50.000000,1.0,4.000000,1.0,insects,no,solitary,no,Bembecinus_tridens,WASPS,1.496160,9.0,0.0,0.188987

In [37]:
planta_polinizador_bruto.isna().sum()

crop             0
type             0
season           0
diameter         0
corolla          0
colour           0
nectar           0
b.system         0
s.pollination    0
inflorescence    0
composite        0
visitor          0
guild            0
tongue           0
body             0
sociality        0
feeding          0
dtype: int64

In [38]:
traços_plantas_bruto = planta_polinizador_bruto.iloc[:, :11]
traços_plantas_bruto.columns.values[0] = "planta"
traços_plantas_bruto['planta'] = traços_plantas_bruto['planta'].astype('category')
traços_plantas_bruto

,planta,type,season,diameter,corolla,colour,nectar,b.system,s.pollination,inflorescence,composite
0,Vaccinium_corymbosum,arboreous,sprisum,72.784872,0.0,4.000000,1.0,insects,no,yes,no
1,Vaccinium_corymbosum,arboreous,sprisum,55.424141,0.0,4.000000,1.0,insects,no,yes,no
2,Brassica_napus,herbaceous,summer,12.500000,1.0,1.000000,1.0,wind/insects,no,yes,no
3,Brassica_napus,herbaceous,summer,12.500000,1.0,1.000000,1.0,wind/insects,no,yes,no
4,Brassica_napus,herbaceous,summer,12.500000,1.0,1.000000,1.0,wind/insects,no,yes,no
...,...,...,...,...,...,...,...,...,...,...,...
791,Allium_oleraceum,herbaceous,summer,60.001037,0.0,2.746336,1.0,insects,no,yes,no
792,Jatropha_curcas,arboreous,spriaut,2.000000,1.0,3.000000,1.0,insects,no,yes,no
793,Malus_domestica,arboreous,spring,35.000000,1.0,4.000000,1.0,insects,no,yes,no
794,Phaseolus_coccineus,herbaceous,summer,16.993078,1.0,4.000000,1.0,insects,no,yes,no
795,Capparis_spinosa,arboreous,summer,50.000000,1.0,4.000000,1.0,insects,no,solitary,no

In [39]:
traços_insetos_bruto = planta_polinizador_bruto.iloc[:, 11:]
traços_insetos_bruto.columns.values[0] = "inseto"
traços_insetos_bruto['inseto'] = traços_insetos_bruto['inseto'].astype('category')
traços_insetos_bruto

                      inseto       guild    tongue  body  sociality   feeding
0           Andrena_wilkella  ANDRENIDAE  1.872272  10.5        0.0  2.000000
1        Andrena_barbilabris  ANDRENIDAE  3.465985  10.5        0.0  0.000000
2          Andrena_cineraria  ANDRENIDAE  7.436739  12.0        0.0  0.000000
3           Andrena_flavipes  ANDRENIDAE  6.738133  11.0        0.0  0.000000
4            Andrena_gravida  ANDRENIDAE  8.135346  13.0        0.0  0.000000
..                       ...         ...       ...   ...        ...       ...
791  Dolichovespula_saxonica       WASPS  5.777719  13.0        1.0  0.000000
792       Bembecinus_tridens       WASPS  5.232198   9.0        0.0  0.080110
793         Vespula_vulgaris       WASPS  5.381072  12.5        1.0  0.000000
794    Philanthus_triangulum       WASPS  7.998989  15.0        0.0  0.000000
795       Bembecinus_tridens       WASPS  1.496160   9.0        0.0  0.188987

[796 rows x 6 columns]

In [40]:
matriz_interacao = pd.crosstab(index=traços_plantas_bruto['planta'], columns=traços_insetos_bruto['inseto'])
matriz_interacao

inseto,Adalia_decempunctata,Agapanthia_villosoviridescens,Agapostemon_texanus,Agapostemon_virescens,Aglais_urticae,Andrena_barbilabris,Andrena_bicolor,Andrena_chrysosceles,Andrena_cineraria,Andrena_cingulata,...,Volucella_inanis,Volucella_pellucens,Xylocopa_aestuans,Xylocopa_amedaei,Xylocopa_cearensis,Xylocopa_fenestrata,Xylocopa_hottentotta,Xylocopa_valga,Xylocopa_violacea,Xylocopa_virginica
planta,,,,,,,,,,,,,,,,,,,,,
Allium_cepa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
Allium_oleraceum,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
Amomum_subulatum,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Anacardium_occidentale,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Arachis_hypogaea,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vicia_faba_major,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Vigna_unguiculata,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Vitis_vinifera,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zea_mays,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ziziphus_mauritiana,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [41]:
dados = createCommunity(traços_plantas_bruto, traços_insetos_bruto, matriz_interacao)
dados

{'data':                           X                         Y       type   season  \
 0      Vaccinium_corymbosum          Andrena_wilkella  arboreous  sprisum
 1      Vaccinium_corymbosum       Andrena_barbilabris  arboreous  sprisum
 2      Vaccinium_corymbosum         Andrena_cineraria  arboreous  sprisum
 3      Vaccinium_corymbosum          Andrena_flavipes  arboreous  sprisum
 4      Vaccinium_corymbosum           Andrena_gravida  arboreous  sprisum
 ...                     ...                       ...        ...      ...
 20475        Coffea_arabica  Dolichovespula_norwegica  arboreous   spring
 20476        Coffea_arabica   Dolichovespula_saxonica  arboreous   spring
 20477        Coffea_arabica        Bembecinus_tridens  arboreous   spring
 20478        Coffea_arabica          Vespula_vulgaris  arboreous   spring
 20479        Coffea_arabica     Philanthus_triangulum  arboreous   spring

         diameter  corolla  colour  nectar      b.system s.pollination  \
 0      72.784872      0.0     4.0     1.0       insects            no
 1      72.784872      0.0     4.0     1.0       insects            no
 2      72.784872      0.0     4.0     1.0       insects            no
 3      72.784872      0.0     4.0     1.0       insects            no
 4      72.784872      0.0     4.0     1.0       insects            no
 ...          ...      ...     ...     ...           ...           ...
 20475  -6.782379      2.0     4.0     1.0  wind/insects            no
 20476  -6.782379      2.0     4.0     1.0  wind/insects            no
 20477  -6.782379      2.0     4.0     1.0  wind/insects            no
 20478  -6.782379      2.0     4.0     1.0  wind/insects            no
 20479  -6.782379      2.0     4.0     1.0  wind/insects            no

       inflorescence composite       guild    tongue  body  sociality  feeding  \
 0               yes        no  ANDRENIDAE  1.872272  10.5        0.0  2.00000
 1               yes        no  ANDRENIDAE  3.465985  10.5        0.0  0.00000
 2               yes        no  ANDRENIDAE  7.436739  12.0        0.0  0.00000
 3               yes        no  ANDRENIDAE  6.738133  11.0        0.0  0.00000
 4               yes        no  ANDRENIDAE  8.135346  13.0        0.0  0.00000
 ...             ...       ...         ...       ...   ...        ...      ...
 20475           yes        no       WASPS  6.800086  14.5        1.0  0.00000
 20476           yes        no       WASPS  5.777719  13.0        1.0  0.00000
 20477           yes        no       WASPS  5.232198   9.0        0.0  0.08011
 20478           yes        no       WASPS  5.381072  12.5        1.0  0.00000
 20479           yes        no       WASPS  7.998989  15.0        0.0  0.00000

          target
 0      negative
 1      negative
 2      negative
 3      negative
 4      negative
 ...         ...
 20475  negative
 20476  positive
 20477  negative
 20478  negative
 20479  negative

 [20480 rows x 18 columns],
 'target': 0        negative
 1        negative
 2        negative
 3        negative
 4        negative
            ...
 20475    negative
 20476    positive
 20477    negative
 20478    negative
 20479    negative
 Name: target, Length: 20480, dtype: object,
 'type': 'Classification',
 'class': ['Community', 'Classification']}

In [42]:
dados['target'].value_counts()

target
negative    19684
positive      796
Name: count, dtype: int64

In [43]:
dados['data'].columns

Index(['X', 'Y', 'type', 'season', 'diameter', 'corolla', 'colour', 'nectar',
       'b.system', 's.pollination', 'inflorescence', 'composite', 'guild',
       'tongue', 'body', 'sociality', 'feeding', 'target'],
      dtype='object')

# Rodando os modelos de classificação

In [ ]:
classification = [class_community_C1, class_community_C2, class_community_C3, class_community_C4_high,
class_community_C4_mid, class_community_C4_low]
sampling_class = [None,0.75,None,None,0.75,0.75]
run_multiple_classifications(classification,sampling_class)

Iniciando a classificação para: C1
Aplicando modelos...

c:\Users\maria\Desktop\PythonTraitMatching-Prediction\machine_learning.py:128: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = class_community['data'].iloc[:, -1].replace({'positive': 1.0, 'negative': 0.0})
c:\Users\maria\Desktop\PythonTraitMatching-Prediction\machine_learning.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pd.concat([results_df, pd.DataFrame([{'Model': 'DNN',

              Model  Accuracy  F1_Score  Precision    Recall       AUC
0               DNN  0.530571  0.253045   0.441556  0.180509  0.495155
1               CNN  0.516000  0.413372   0.452407  0.386588  0.499293
2        NaiveBayes  0.498286  0.479341   0.446868  0.517283  0.500177
3  GradientBoosting  0.526857  0.368405   0.456237  0.309212  0.509563
4      RandomForest  0.544571  0.133132   0.445047  0.078754  0.501206
5               KNN  0.480000  0.544362   0.447061  0.695908  0.494315
Resultados salvos em: C1.xlsx
Iniciando a classificação para: C2
Aplicando modelos...

c:\Users\maria\Desktop\PythonTraitMatching-Prediction\machine_learning.py:128: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = class_community['data'].iloc[:, -1].replace({'positive': 1.0, 'negative': 0.0})
c:\Users\maria\Desktop\PythonTraitMatching-Prediction\machine_learning.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pd.concat([results_df, pd.DataFrame([{'Model': 'DNN',

              Model  Accuracy  F1_Score  Precision    Recall       AUC
0               DNN  0.940401  0.946052   0.976633  0.917958  0.975814
1               CNN  0.964562  0.968270   0.990282  0.947390  0.989733
2        NaiveBayes  0.728300  0.690497   0.988479  0.530859  0.931042
3  GradientBoosting  0.941831  0.948993   0.950998  0.947074  0.979673
4      RandomForest  0.841242  0.873227   0.804953  0.954902  0.941226
5               KNN  0.933060  0.938047   0.995119  0.887260  0.943006
Resultados salvos em: C2.xlsx
Iniciando a classificação para: C3
Aplicando modelos...

c:\Users\maria\Desktop\PythonTraitMatching-Prediction\machine_learning.py:128: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = class_community['data'].iloc[:, -1].replace({'positive': 1.0, 'negative': 0.0})
c:\Users\maria\Desktop\PythonTraitMatching-Prediction\machine_learning.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pd.concat([results_df, pd.DataFrame([{'Model': 'DNN',

              Model  Accuracy  F1_Score  Precision    Recall       AUC
0               DNN  0.751643  0.704297   0.727874  0.683995  0.819123
1               CNN  0.771786  0.724855   0.758022  0.695036  0.847658
2        NaiveBayes  0.672000  0.699675   0.579885  0.882071  0.732760
3  GradientBoosting  0.713286  0.657661   0.680966  0.636320  0.780138
4      RandomForest  0.579857  0.103219   0.689258  0.056240  0.706920
5               KNN  0.547071  0.591345   0.485294  0.756721  0.593649
Resultados salvos em: C3.xlsx
Iniciando a classificação para: C4
Aplicando modelos...

c:\Users\maria\Desktop\PythonTraitMatching-Prediction\machine_learning.py:128: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = class_community['data'].iloc[:, -1].replace({'positive': 1.0, 'negative': 0.0})
c:\Users\maria\Desktop\PythonTraitMatching-Prediction\machine_learning.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pd.concat([results_df, pd.DataFrame([{'Model': 'DNN',

              Model  Accuracy  F1_Score  Precision    Recall       AUC
0               DNN  0.753286  0.711727   0.725089  0.701478  0.822514
1               CNN  0.775643  0.737826   0.750255  0.725944  0.850263
2        NaiveBayes  0.688214  0.707819   0.597514  0.868144  0.747202
3  GradientBoosting  0.716571  0.667243   0.682034  0.653202  0.782605
4      RandomForest  0.580929  0.129659   0.677283  0.071921  0.704368
5               KNN  0.539000  0.585392   0.480817  0.748276  0.583123
Resultados salvos em: C4.xlsx
Iniciando a classificação para: C4_2
Aplicando modelos...

c:\Users\maria\Desktop\PythonTraitMatching-Prediction\machine_learning.py:128: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = class_community['data'].iloc[:, -1].replace({'positive': 1.0, 'negative': 0.0})

# Rodando os modelos de regressão

In [ ]:
regression = [class_community_R1, class_community_R2, class_community_R3, class_community_R4_high,
class_community_R4_mid, class_community_R4_low]
sampling_r = [{ 4.0: 400, 3.0: 585, 2.0: 900}, None, None, None, None, None]
run_multiple_regressions(regression, sampling_r)

# Caso Real

In [ ]:
run_real_data_classifications(dados, 0.75)

In [ ]:
main_real_data_importance(dados, 0.75)

# Hiperparâmetros

In [ ]:
run_multiple_classification_hiper(classification, sampling_class)

In [ ]:
run_multiple_regressions_hiper(regression, sampling_r)